Resources:
  CreateGiftQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - SQS:*
            Resource: !GetAtt SetGiftQueue.Arn
            Principal:
              AWS:
                - !Ref AWS::AccountId
          - Effect: Allow
            Principal:
              AWS:
                - '*'
            Action:
              - SQS:SendMessage
            Resource: !GetAtt SetGiftQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn:
                  - !Ref ClientCreatedTopic
                  - !Ref ClientUpdatedTopic
      Queues:
        - !Ref SetGiftQueue
